name: Handle issues
on: issues
jobs: 
    info:
        runs-on: ubuntu-latest
        steps:             
            - name: Display Information
              run: echo "${{ toJson(github.event) }}"
